trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: "DotNet Build"
  inputs:
    command: 'build'
    projects: '**/SigniFlow.EventHandler.csproj'
- task: mirror-git-repository-vsts-task@1
  displayName: 'Mirror to GitHub'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/SigniFlow/SigniFlow%20Event%20Handler%20Library/_git/SigniFlow%20Event%20Handler%20Library'
    sourceGitRepositoryPersonalAccessToken: '$(devops-token)'
    destinationGitRepositoryUri: 'https://github.com/SigniFlow/Event-Handler-Library'
    destinationGitRepositoryPersonalAccessToken: '$(github-token)'
- task: DotNetCoreCLI@2
  displayName: 'NuGet Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/SigniFlow.EventHandler.csproj'
    versioningScheme: 'off'
- task: NuGetAuthenticate@1
- script: dotnet nuget push --api-key AzureArtifacts --source NuGet.org '$(Build.ArtifactStagingDirectory)/**/*.nupkg'