trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/SigniFlow/SigniFlow%20Event%20Handler%20Library/_git/SigniFlow%20Event%20Handler%20Library'
    sourceGitRepositoryPersonalAccessToken: '$(devops-token)'
    destinationGitRepositoryUri: 'https://github.com/SignFlow/Event-Handler-Library'
    destinationGitRepositoryPersonalAccessToken: '$(github-token)'
- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'NuGet.org'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'